# Numerični Python - NumPy

NumPy je odprtokodna knjižnica, ki predstavlja standard na področju obdelave numeričnih podatkov v Pythonu za potrebe inženirstva in znanosti. Knjižnico uporabljajo tudi številne druge popularne Python knjižnice, kot so SciPy, Pandas, Matplotlib in številne druge. 

Osnovna podatkovna struktura, ki jo uvaja knjižnica NumPy je n-dimenzionalno polje homogenih elementov (`ndarray`), kar pomeni, da so vsi elementi v polju enakega podatkovnega tipa. NumPy array omogoča zelo učinkovito izvajanje operacij nad polji in zagotavlja bogato knjižnico matematičnih funkcij, s katerimi lahko obdelujemo podatke v n-dimenzonalnih poljih. 

Za razliko od običajnih Python seznamov (podatkovni tip `list`) je izvajanje operacij nad `ndarray` mnogo hitrejše in tudi prostorsko mnogo bolj učinkovito. 


Več o tem na spletu:
> [Kaj je NumPy?](https://numpy.org/doc/stable/user/whatisnumpy.html)

### Namestitev

Če knjižnice nimamo nameščene, jo pred prvo uporabo namestimo s pip:

```
pip install numpy
```


### Uporaba

Knjižnico NumPy običajno uvozimo v celoti in za poimenovanje običajno uporabimo alias 'np'. Funkcionalnosti nato uporabljamo s sklicevanjem na knjižnico.

In [3]:
import numpy as np

## n-dimenzionalna polja

### Ustvarjanje polja

Polje `ndarray` lahko ustvarimo in napolnimo s podatki na več načinov. Največkrat bomo to naredili s pretvorbo običajnih Python podatkovnih struktur, kot sta `list` ali `tuple`, ali pa bomo uporabili funkcije za ustvarjanje polja, kot so `arange`, `ones`, `zeros` in številnih (okrog 40) drugih. Novo polje lahko ustvarimo tudi iz obstoječih `ndarray` ali z uvozom podatkov. 

Do posameznega elementa v polju lahko dostopamo z uporabo indeksov. Upoštevati moramo, da se štetje elementov vedno začne z vrednostjo indeksa 0. Podatkovna struktura nam omogoča zelo fleksibilen dostop do elementov polj višjih dimezij (2 in več). 

V nadaljevanju si bomo ogledali nekaj primerov.

Več o tem na spletu:
> [Ustvarjanje ndarray](https://numpy.org/doc/stable/user/basics.creation.html)


#### Pretvorba iz seznama
Iz običajnih seznamov ali n-teric lahko `ndarray` ustvarimo s funkcijo `array()`.

In [5]:
# 1d polje
a = np.array([1, 2, 3, 4])

# 2d polje
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 3d polje
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

#### Funkcije za ustvarjanje 1D polja

Zaporedja celih števil lahko v Pythonu ustvarimo s funkcijo `range(od, do, korak)`. 

Podobno lahko ustvarimo novo polje, ki vsebuje zaporedje števil z enakomernim korakom s funkcijo `arange(od, do, korak)`. V NumPy se funkcija imenuje drugače, da se razlikuje od običajne funkcije `range()`. Pomembna razlika je tudi ta, da `arange()` lahko ustvarja zaporedja števil z decimalno vejico in ne le zaporedja celih števil.

Spomnimo se, da intevale od-do določamo kot zaprte navzdol in odprte navzgor. Torej v našem primeru [5, 6) in kar pomeni, da zgornja meja več ni znotraj intervala ustvarjenih števil. 

Nekaj primerov:

In [189]:
np.arange(5, 6, 0.1) 

array([5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9])

In [70]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [76]:
np.arange(3, 7)

array([3, 4, 5, 6])

#### Funkcije za ustvarjanje 2D polja

Primera prikazujeta uporabo funkcije za ustvarjanje identitetne matrike ter diagonalne matrike.

In [80]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### Funkcije za polnjenje (nevtralnega) polja

Večkrat potrebujemo polja, ki so nevtralna za seštevanje ali množenje, torej polja ki vsebujejo samo ničle ali samo enice. 

In [92]:
np.zeros(4)

array([0., 0., 0., 0.])

In [100]:
np.zeros((3, 3))  # dimenzijo podamo kot n-terico, zato sta dimenziji v oklepaju

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [102]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Kopiranje obstoječega polja
Obstoječe polje lahko v celoti ali deloma uporabimo za ustvarjanje novega polja. Vendar je treba upoštevati, da je novo polje samo drugi pogled na obstoječe podatke. Če spreminjamo podatke v enem polju, se bodo spremembe odražale tudi v drugem. 

Primer:
Ustvarimo 1d polje `a` s štirimi elementi. Iz polja `a` ustvarimo polje `b` tako, da `b` vsebuje elemente polja `a` od indeksa 2 naprej.  

In [161]:
a = np.array([1, 2, 3, 4])
b = a[2:]

Poglejmo vrednosti obeh polj.

In [145]:
a

array([1, 2, 3, 4])

In [147]:
b

array([3, 4])

Če sedaj spremenimo drugi element polja `a`, se bo sprememba odražala tudi v polju `b`.

In [163]:
a[2] = 99
a

array([ 1,  2, 99,  4])

In [165]:
b  # zaradi spremembe v a, se spremeni tudi b

array([99,  4])

Če želimo narediti pravo kopijo, moramo uporabiti funkcijo `copy()`.

In [153]:
c = a[2:].copy()
a[3] = 7  #spremenimo zadnji element a
a

array([ 1,  2, 99,  7])

In [157]:
c  # sprememba a NI vplivala na c! 

array([99,  4])

#### Pretvorba dimenzij polja

Obstoječe dimenzije polja lahko preverimo z atributom `shape`. Vrednost `shape` je n-terica, katere vrednosti so velikosti posamezne dimenzije polja. V primeru 2D polja to pomeni par, ki navede število vrstic in število stolpcev.   

Shape omogoča tudi pretvorbo dimenzij polja. Če določimo novo vrednost atributa `shape`, bomo s tem polje preoblikovali v novo obliko. Pri tem moramo sami poskrbeti, da nove dimenzije omogočajo hranjenje vseh elementov polja in da število elementov ne presega števila razpoložljivih elementov polja. 

Na primeru si poglejmo, kako ustvariti vektor [1, 2, 3, 4, 5, 6, 7, 8, 9], ki ga pretvorimo v matriko 3x3.

In [174]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
a.shape # dimezija polja a 

(9,)

In [187]:
a.shape = (3, 3) # paziti moramo, da število elementov polja ostane enako (9=3x3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Indeksiranje

Do elementov polja dostopamo z uporabo indeksov. To so zaporedna števila elementov v polju. Pomembno je upoštevati, da se vsi indeksi začnejo z 0. 

NumPy omogoča zelo fleksibilno indeksiranje, oziroma izbor elementov. 

#### Indeksiranje posamičnih elementov
Pri naslavljanju posamičnega elementa moramo določiti vse dimenzije. 

In [216]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[4]

5

Ustvarimo 2d polje dimenzij 3x3:

In [218]:
b = np.arange(1, 10)
b.shape = (3, 3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Izberemo element v prvi vrstici in drugem stolpcu. Za razliko od običajnih seznamov bodimo pozorni, da indekse za vse dimenzije pišemo v ene oglate oklepaje, indekse različnih dimenzij med seboj ločimo z vejico. 

In [225]:
b[1,2] 

6

#### Indeksiranje delov polja (rezanje ali 'slicing')
V polju lahko naslovimo tudi več kot en element, npr. vrstico, stolpec, ali več celih vrstic ali stolpcev ali samo njihovih delov. Kot rezultat dobimo rezino originalnega polja. 

Pravilo rezanja je podobno rezanju običajnih Python seznamov, torej v oklepaje zapišemo [od: do: korak]. Ker je `ndarray` lahko večdimenzinalno polje, elemente izbiramo po vseh dimenzijah.

#### Izbira elementov v polju 1D

In [6]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

In [235]:
a[2:5]

array([3, 4, 5])

In [239]:
a[2:7:2]

array([3, 5, 7])

Negativni indeksi predstavljajo štetje iz desne strani. Pozitivne in negativne indekse lahko tudi kombiniramo.

In [248]:
a[-5: 4]

array([3, 4])

In [250]:
a[-5: -2]

array([3, 4, 5])

In [252]:
a[1: -1]

array([2, 3, 4, 5, 6])

Če želimo začeti z indeksom 0 ali končati pri največjem indeksu, lahko indeks tudi izpustimo.

In [257]:
a[:4]

array([1, 2, 3, 4])

In [7]:
a[3:]

array([4, 5, 6, 7])

In [261]:
a[::2]

array([1, 3, 5, 7])

#### Izbira dela večdimenzionalnih polj

V večdimenzionalnih poljih vse nabore indeksov zapišemo v en oklepaj.

Naj bo polje a velikosti 3x3.

In [9]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # 2d polje 3x3 

Za izbiro prve dimezije sicer lahko uporabimo samo en indeks:

In [272]:
a[2]

array([7, 8, 9])

Vendar je pri uporabi več dimezionalnih polj običajno, da navedemo indekse za vse dimenzije. 

Če želimo izbrati vse elemente druge vrstice, navedemo vrstico in nato navedemo še vse stolpce. Takšen pristop je univerzalen in ga lahko uporabimo tako za izbiro vrstic kot stolpcev in elementov višjih dimenzij.

In [301]:
a[2, :]  # elementi druge vrstice in vseh stolpcev

array([7, 8, 9])

Izberemo vse vrstice in v teh vrsticah izberemo vsak drugi stolpec:

In [299]:
a[:, ::2]  #elementi vseh vrstic in vseh stolpcev s korakom 2

array([[1, 3],
       [4, 6],
       [7, 9]])

Izberemo prvi stolpec:

In [297]:
a[:, 1]   # elementi iz vseh vrstic in prvega stolpca

array([2, 5, 8])

Elemente lahko izberemo tudi z navajanjem seznamov koordinat. V 2d polju to pomeni, da naštejemo kombinacije vrstic in stolpcev za vse elemente, ki jih želimo prebrati, torej naštejemo vse vrstice in k vsakemu indeksu vrstice ustrezen indeks stolpca. V primeru bomo iz vrstice 0 prebrali podatek v stolpcu 0 ter iz vrstice 2 prebrali podatek v stolpcu 1 in rezultat bo torej polje z dvema izbranima elementoma:

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Seznam vrstic je [0, 2] in seznam stolpcev je [0, 1]. Soležni elementi vrstice in stolpca predstavljata par koodinat izbranega elementa. Iz zapisanega sledi, da izbiramo elementa (0,0) in (2,1).

In [10]:
a[[0,2], [0,1]] # izberemo elementa a[0,0] in a[2,1]

array([1, 8])

### Logično indeksiranje
Elemente polja lahko izbiramo tudi tako, da namesto številk indeksov navedemo, katere elemente želimo in katerih ne želimo uvrstiti v rezultat. 

In [10]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

izbrani = [True, False, True, False, True, False, True, True, True ]

a[izbrani]

array([1, 3, 5, 7, 8, 9])

Logično indeksiranje je lahko zelo uporabno, kadar želimo v polju izbrati elemente glede na določeno lastnost. Na primer, če bi želeli izbrati vse elemente, ki so večji od izbrane vrednosti ali če bi želeli izbrati vsa soda števila, bi to preprosto storili z logičnim indeksiranjem. Priprava seznama vrednosti True/False je namreč z uporabo polj zelo preprosta, vendar za to potrebujemo še nekaj znanja o uporabi operatorjev nad polji, kar je tema naslednjega poglavja.

__Primer:__ \
Za konec poglejmo še praktičen primer uporabe logičnega indeksiranja. Podan je seznam vrednosti $sez$, vse vrednosti seznama, ki presegajo število 10, postavimo na 10 (odrežemo visoke vrednosti).

Z navadnim seznamom lahko to naredimo v zanki:

In [11]:
sez = [1, 20, 3, 40, 5, 60, 7, 80, 9]

for i, el in enumerate(sez):
    if el > 10:
        sez[i] = 10

print(sez)

[1, 10, 3, 10, 5, 10, 7, 10, 9]


Seznam lahko pretvorimo v `ndarray`. V polju bomo izbrali samo tiste elemente, ki so večji od 10. Vse izbrane elemente lahko spremenimo z enim samim prireditvenim stavkom.

In [13]:
sez = [1, 20, 3, 40, 5, 60, 7, 80, 9]
sez_np = np.array(sez)

izbrani = sez_np > 10
print(izbrani)

sez_np[izbrani] = 10
print(sez_np)

[False  True False  True False  True False  True False]
[ 1 10  3 10  5 10  7 10  9]
